### ISSUE TITLE
startingAngleInRadian and endingAngleInRadian can not be null

### ISSUE THREAD

**Issue by ganeshchenniah** [hasan-hm1/circular_menu#14] opened 2020-12-13 13:11 UTC
Hi ,

What is the angle to be given for bottom center widget which has 5 menu items . It was working well before, now i m getting error

**Comment by hasan-hm1** [comment] 2020-12-13 14:50
Hi @ganeshchenniah  
Thanks for creating this issue ,
Please do not give any angle , default values are enough in this case , like this :
```
CircularMenu(
        items: [
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
        ],
        backgroundWidget: Container(),
      )
```

**Comment by ganeshchenniah** [comment] 2020-12-19 07:34
Hi ,

Sorry for delayed response , if i dont specify startingAngleInRadian and endingAngleInRadian , it is throwing these values can't be null . So i specified 0,0. It is now circluar . But i want all 5 items in 180 degree. Because i keep circluar_menu widget at the bottomcenter alignment .

**Comment by hasan-hm1** [comment] 2020-12-19 12:38
Hi @ganeshchenniah ,
Please notice that `startingAngleInRadian  ` and  `endingAngleInRadian  ` are optional parameters , so you do not have to specify any value unless you need a custom angle (5 items in 180 degree at the bottomcenter is not so !) .
It throws ` startingAngleInRadian and endingAngleInRadian can not be null ` only in two cases :
1. null is passed explicitly to  `startingAngleInRadian` or `endingAngleInRadian  ` or both .
2. a valid value is passed to either `startingAngleInRadian  ` or  `endingAngleInRadian  ` , so by default the other one is assigned to null , and the error is thrown .

For your usecase you just need to pass the five items and I gurantee it will work fine , because the default alignment is `Alignment.bottomCenter` and the default angle for this alignment is 180 degree .
Just like this :
```
CircularMenu(
        items: [
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
          CircularMenuItem(onTap: () {}),
        ],
        backgroundWidget: Container() , // whatever widget
      )
```
If the issue is not resolved and you still get the error , Please do not hesitate to provider your code (the circular menu part ) so I can figure out what is happening .

**Comment by ganeshchenniah** [comment] 2020-12-19 17:42
Hi,

I have tried you example code given in this repository , they are also throwing the same error . 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following message was thrown building _BodyBuilder:
startingAngleInRadian and endingAngleInRadian can not be null

**Comment by hasan-hm1** [comment] 2020-12-21 08:29
Hi  @ganeshchenniah  ,
The example code works fine without any errors  I just tried it again  , no problem with circular menu rather it may be related to something else .
Please paste your code here so I can figure out what is happening , or create a project on an online Flutter editor (like  [this](https://flutlab.io/) ) and share it with me .
Thanks.

**Comment by ganeshchenniah** [comment] 2020-12-24 06:35
Following is my code . 

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.17134.1610], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!



CircularMenu(
        //FIXME : Asked github user , waiting For his reply
        //  startingAngleInRadian: 0,
        //  endingAngleInRadian: 0,
        alignment: Alignment.center,
     //   toggleButtonColor:  CustomColors.containerDark,
        backgroundWidget: Padding(
          padding: const EdgeInsets.all(8.0),
          child: RepaintBoundary(
            key: screenshotKey,
            child: Stack(children: [
              Stack(children: [
                PhotoView(
                  //  initialScale: PhotoViewComputedScale.contained,
                  imageProvider: FileImage(widget.imageFile),
                  scaleStateController: scaleStateController,
                  backgroundDecoration: BoxDecoration(color: Colors.white),
                ),
                _signatureEnable
                    ? Positioned(
                        top: yPosition,
                        left: xPosition,
                        child: XGestureDetector(
                          onMoveUpdate: (localPos, position, localDelta, delta) {
                            Offset offset = localPos;
                            print('onMoveUpdate - pos: ' + localPos.toString());
                            print(
                                'onMoveUpdate - dx  ${offset.dx} dy ${offset.dy}');
                            setState(() {
                              xPosition = offset.dx;
                              yPosition = offset.dy;
                            });
                          },
                          onScaleUpdate: (changedFocusPoint, scale, rotation) {
                            print(
                                'onScaleUpdate - changedFocusPoint:  $changedFocusPoint ; scale: $scale ;Rotation: $rotation');
                            setState(() {
                              //Uncomment For rotating this widget
                              //  _rotation = rotation;
                              _scale = viewScale;
                            });
                          },
                          child: Transform(
                              transform: Matrix4.diagonal3(
                                  v64.Vector3(_scale, _scale, _scale))
                                ..rotateZ(_rotation),
                              //   scale: _scale,
                              //   angle: _rotation,
                              child: InkWell(
                                child: Container(
                                  color: Colors.transparent,
                                  child: Image.memory(data),
                                ),
                              )),
                        ))
                    : Container()
              ]),
              //
              //
            ]),
          ),
        ),
        items: [
          CircularMenuItem(
              icon: Icons.rotate_left,
              color: CustomColors.secondaryTextColor.withOpacity(.8),
              onTap: () {
                setState(() {
                  _rotation = _rotation - 0.1;
                });
              }),
          CircularMenuItem(
              icon: Icons.rotate_right,
              color: CustomColors.secondaryTextColor.withOpacity(.8),
              onTap: () {
                setState(() {
                  _rotation = _rotation + 0.1;
                });
              }),
          CircularMenuItem(
              icon: Icons.add_circle,
              color: CustomColors.secondaryTextColor.withOpacity(.8),
              onTap: () {
                setState(() {
                  _scale = _scale + 0.1;
                });
              }),
          CircularMenuItem(
              icon: Icons.remove_circle,
              color: CustomColors.secondaryTextColor.withOpacity(.8),
              onTap: () {
                setState(() {
                  _scale = _scale - 0.1;
                });
              }),
          CircularMenuItem(
              icon: Icons.local_printshop,
              color: CustomColors.secondaryTextColor.withOpacity(.8),
              onTap: () async {
                String result = await _takeScreenShot();
                goBack();
//                if (result != null) {
//                  showDialog(
//                      context: context, builder: (context) => ShareImage());
//                }

//                await showDialog(
//                    context: context,
//                    builder: (_) => AssetGiffyDialog(
//                          image: Image.asset('assets/send_animation.gif'),
//                          title: Text(
//                            'Forward',
//                            style: TextStyle(
//                                fontSize: 22.0, fontWeight: FontWeight.w600),
//                          ),
//                          description: Text('Description'),
//                          entryAnimation: EntryAnimation.TOP,
//                          onOkButtonPressed: () {
//
//                          },
//                        ));
              })
        ],
      )

**Comment by nibuen** [comment] 2021-02-16 19:25
This error happens with alignment default case `throw 'startingAngleInRadian and endingAngleInRadian can not be null';`  The `widget.alignment.toString()` is 'Alignment.bottomCenter' on my device so matches no case.

**Comment by jinjilynn** [comment] 2021-03-26 15:03
> This error happens with alignment default case `throw 'startingAngleInRadian and endingAngleInRadian can not be null';` The `widget.alignment.toString()` is 'Alignment.bottomCenter' on my device so matches no case.

yeah, the returned string of method 'toString()'  is prefixed with 'Alignment.'
![image](https://user-images.githubusercontent.com/12596042/112651226-28baec00-8e87-11eb-84aa-fc9fd579089d.png)

**Closed as completed** 2024-04-15 07:48 UTC
Labels: question
